# Generated by Django 3.2.9 on 2021-12-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('I', 'Internal'), ('L', 'Local')], default='L', max_length=30),
        ),
    ]
