# Generated by Django 3.2.9 on 2021-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_supplier_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('I', 'International'), ('L', 'Local')], default='L', max_length=13),
        ),
    ]
